pipeline {
    agent any

    tools
    {
        node 'node'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your version control system (e.g., Git)
                git 'https://github.com/KoushaliyaSree/HelloWorldJenkins.git'
            }
        }



        stage('Install Dependencies') {
            steps {
               
                // Install dependencies using npm
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                // Build the React application
                sh 'npm run build'
            }
        }
        stage('test') {
            steps {
                // Build the React application
                echo "test"
            }
        }

    
    }
}